### ISSUE TITLE
Does it work with selects?

### ISSUE THREAD

**Issue by davidray** [nervetattoo/jquery-autosave#10]
First of all, thanks for doing this. It's working great for certain parts of my form, but I'm having trouble with select fields (dropdowns) - the value is not being included in my ajax call. Any idea what's going on there? Any suggestions for where to look in the code to figure this out?

If it helps, I added console.log($inputs); at line 559 and $inputs is including only the first option, not the selected option. If I can make this work I'll send you a pull request.

Thanks!

Dave

**Comment by kflorence** [comment]
It does indeed work with drop downs. Which callback handler are you using? Which browser?

**Comment by davidray** [comment]
I'm using the latest chrome with the defaults, except for this:

```$('.page#businesses_page #business-info form').autosave(
    callbacks: {
      save: {
        method: "ajax",
        options: {
          success: ->  console.log("saved!"),
          failure: -> alert("We're not sure why, but we couldn't save that. We'll try to save again in a few seconds."),
          type: "PUT"
        }
      }
    }

``````
Here's the html for my select:
 ```<select id="business_market_id" name="business[market_id]"><option value="1">Indianapolis, IN</option>
                    <option value="2">Chicago, IL</option></select>```
``````

**Comment by kflorence** [comment]
Is that your actual code? If so, please refer to http://api.jquery.com/jQuery.ajax/ for examples on what you can pass into the "options" hash of the "ajax" method.

**Comment by davidray** [comment]
Yeah, it's coffeescript, so if you're not familiar with that I'll make it simply javascript:
```$('.page#businesses_page #business-info form').autosave(
    callbacks: {
      save: {
        method: "ajax",
        options: {
          type: "PUT"
        }
      }
    }
  );

```

Basically, all my text fields are saving great, but the selected value for the market isn't serialized at all.
```

**Comment by davidray** [comment]
Just for kicks, I went with all defaults, and it still doesn't submit a value for the selected item, but it does for any text fields I edit.

**Comment by kflorence** [comment]
Hmm, that is odd. I'm wondering if it has something to do with the brackets in the name (which is perfectly valid). I'll write up some test cases for this and see if they fail. I'll keep you posted in here.

**Comment by kflorence** [comment]
I have confirmed this bug, even without brackets present. I'll work on a fix tonight. Thanks for noticing! :)

**Comment by davidray** [comment]
Thanks!

**Comment by kflorence** [comment]
Fortunately, this was just a regression from my merge last night. :)
