### ISSUE TITLE
<fieldset> causes extra save()'s

### ISSUE THREAD

**Issue by philfreo** [nervetattoo/jquery-autosave#15]
Working:
http://jsfiddle.net/philfreo/WuhGX/5/

Broken:
http://jsfiddle.net/philfreo/WuhGX/4/

Only difference is a `<fieldset>` tag.

I'm creating a pull request with a failing test. Not sure of the best fix yet - let me know!

**Comment by kflorence** [comment]
Thanks, this was most definitely a bug. I have fixed it here: https://github.com/nervetattoo/jquery-autosave/issues/17
