### ISSUE TITLE
Modify trigger happens on non-value-changing key presses

### ISSUE THREAD

**Issue by philfreo** [nervetattoo/jquery-autosave#18]
Since the `modify` trigger uses `keyup` internally, a lot of extra autosave events are called unnecessarily. For example, pressing control, option, left arrow key, etc. keyboard keys alone shouldn't trigger a save but do.

One way would be to keep track of the before and after values of the input element.

Or take a look at the HTML5 `input` event:

https://developer.mozilla.org/en-US/docs/DOM/DOM_event_reference/input

http://dev.w3.org/html5/spec/common-input-element-apis.html#common-event-behaviors

**Comment by kflorence** [comment]
Thanks. I'll implement this fix in the next version.

**Comment by philfreo** [comment]
Looks like this is all set... thanks @wojcikstefan
