### ISSUE TITLE
Handling save, saved events?

### ISSUE THREAD

**Issue by oschrenk** [nervetattoo/jquery-autosave#2]
Depsite your tremondous readme file, I still don't quote get how to handle events

```
    jQuery(function($) {
        $("form").autosave({
            callbacks: {
                save: {
                    method: "ajax",
                        options: {
                            beforeSend: function (jqXHR, setting) {
                                console.log("before");
                            },
                            complete: function(jqXHR, textStatus) {
                                console.log("complete");
                            }
                        }
                    }
                }
            });

            $('#forename').bind('saved mouseenter', function() {
              console.log("saved?!");
            });
        });
```

I thought events could be handled by using `.bind()`. While `mouseenter` is handled the `saved` event is not.

**Comment by kflorence** [comment]
All of the autosave events are namespaced, so "saved" is actually "saved.autosave" -- this has no effect when triggering the events ("saved" or "saved.autosave" will both work), but I think when binding it needs the full name. This should probably be mentioned somewhere in the readme.

More information here: http://docs.jquery.com/Namespaced_Events

**Comment by oschrenk** [comment]
It even is mentioned in the documentation. I wasn't aware of namespacing in jQuery when binding events.

I still don't quite understand the usage though. I thought the events were triggered by the library. Or do I have to trigger the events manually? The functions are never called although the Ajax request gets completed successfully.

```
<script type="text/javascript">
    jQuery(function($) {
        $("form").autosave();
        });
        $('#forename').bind('saved', function() {
            console.log("saved");
        });
        $('#forename').bind('saved.autosave', function() {
            console.log("saved.autosave");
        });
        $('#forename').bind('save', function() {
            console.log("save");
        });
        $('#forename').bind('save.autosave', function() {
            console.log("save.autosave");
        });
        $('#forename').bind('changed', function() {
            console.log("save");
        });
        $('#forename').bind('changed.autosave', function() {
            console.log("save.autosave");
        });     
</script>
```

**Comment by kflorence** [comment]
Your code above has the closing }); in the wrong place. When that is corrected it should work correctly. We really need more examples, but I haven't had the time to make any lately.

**Comment by kflorence** [comment]
I put up a quick example here: http://kflorence.github.com/jquery-autosave/examples/

**Comment by oschrenk** [comment]
Thanks. That helped.

**Comment by kflorence** [comment]
No problem, happy to help.
