### ISSUE TITLE
request is 'GET' instead of 'POST'

### ISSUE THREAD

**Issue by deniswolf** [nervetattoo/jquery-autosave#21]
I have no idea what is going on: every time I'm trying to trigger 'save' or it's triggered automatically (on 'blur' or whatever) - my server receives 'GET' request with serialized form's data in query.
### form:

``` html
<form method="post" action="/ideas/5079b65aa362a2bb4000000b" class="edit">
<input type="hidden" name="_method" value="put">
<textarea name="idea[text]" placeholder="|" class="idea-text">Some text</textarea>
<input type="submit" value="+"></form>
```
### how I bind 'autosave'

``` javascript
$('form.edit').autosave()
```

any ideas?
it works in the same broken way with just form on page or with `$('form.edit').autosave({method:'post'})
`

**Comment by kflorence** [comment]
You need to configure the "ajax" callback:

``` javascript
$('form.edit').autosave({
   callbacks: {
       save: {
           method: "ajax",
           // Any option that jQuery.ajax accepts can go here
           options: {
               type: "POST"
           }
       }
   }
});
```

**Comment by kflorence** [comment]
Currently autosave does not take into account the form's action attribute, however, this will be built into version 2.0 (in case you were wondering).

:)

**Comment by mcblum** [comment]
Just so I understand, there's no way to use autosave to post data to a different URL?

**Comment by kflorence** [comment]
@mcblum autosave will accept any parameters that jQuery.ajax accepts, including URL.

**Comment by mcblum** [comment]
@kflorence Thanks!
