### ISSUE TITLE
No way to retrieve an autosave instance

### ISSUE THREAD

**Issue by ararog** [nervetattoo/jquery-autosave#23]
Hi, 

I want to retrieve an autosave instance to call the save method from a button click, I would like to have this instance without wait the user change a input or something like that.

How can I retrieve an instance of autosave for this purpose?

**Comment by philfreo** [comment]
I'm doing this:

```
            var autosave = this.$('form').data('autosave');
            if (autosave) autosave.stopInterval();
```

**Comment by kflorence** [comment]
Yep, the best way to get it is through `$( '.element' ).data( 'autosave' )`
