### ISSUE TITLE
posting dataset

### ISSUE THREAD

**Issue by BaseMax** [nervetattoo/jquery-autosave#24]
@nervetattoo @kflorence 

jQuery('form').autosave({
   callbacks: {
       save: {
           method: "ajax",
           // Any option that jQuery.ajax accepts can go here
           options: {
               url: "/ajax/update_contents/save",
               type: "POST"
           }
       }
   }
});

this posts only one element which is modified i want to post entire form elements whenever an element modified or updated.

thanks

**Comment by BaseMax** [comment]
@nervetattoo help

**Comment by BaseMax** [comment]
@kflorence help

**Comment by kflorence** [comment]
This is pretty well documented in the [readme](https://github.com/nervetattoo/jquery-autosave#scope) and spamming me certainly doesn't help.
