### ISSUE TITLE
How to autosave on modified but not more than every 3 seconds

### ISSUE THREAD

**Issue by creativetags** [nervetattoo/jquery-autosave#25]
How do you limit how often it sends the ajax request so it doesn't make too many requests? I'm triggering it when a modification is made but I don't want it to make too many requests while someone is typing.

**Comment by philfreo** [comment]
You can use the `interval` trigger, in combination with the `modified` condition.

**Comment by creativetags** [comment]
Thanks for the suggestion. That seems to stop it from triggering until a field has been modified but once it has been modified it saves every interval. I want the interval to be low e.g. 3 seconds so it doesn't lose something if the user navigates away before saving. Is it possible for it to detect if the field value is different from the last value saved?

**Comment by philfreo** [comment]
I use this setup in production and no, it doesn't continue to save every `interval` - the `modified` condition prevents that.

**Comment by kflorence** [comment]
``` javascript
$("form").autosave({
    trigger: {
        method: "interval",
        options: {
            interval: 3000
        }
    },
    condition: "modified"
});
```

That should work. This will save every 3 seconds as long as a value has been modified.

**Comment by creativetags** [comment]
My code is almost the same as kflorence's:

``` javascript
  jQuery(function($) {
    $("form").autosave({
      callbacks: {
        trigger: {
          method: "interval", 
          options: { 
            interval: 3000            
          }           
        },
        condition: "modified",
        save: {
          method: "ajax",
          options: {
            url: $("form").attr('action'),
            dataType: 'script',
            type: 'PUT',
            success: function() {
              $(".savedindicator").fadeIn("slow");
              $(".savedindicator").fadeOut("slow");
            }
          }
        }
      }
    });
  });
```

After I start typing in a field it saves every 3 seconds even if I stop typing and nothing has changed since the last time. I want it to stop saving when no changes have been made since the last time.

**Comment by philfreo** [comment]
Are you using the latest master? Setup a jsfiddle.

**Comment by creativetags** [comment]
Ok, in setting up a jsfiddle I solved the problem. I was using the minified version but when I swapped to the original it works fine. It seems the minified version is out of date. I minified the original myself and it works fine.

**Comment by creativetags** [comment]
Here's my test: http://jsbin.com/ucobuc/1/edit

**Comment by kflorence** [comment]
I've updated the minified version, sorry about that.

**Comment by creativetags** [comment]
Great, thanks
