### ISSUE TITLE
'interval' trigger with 'modified' condition shouldn't miss out on final modifications

### ISSUE THREAD

**Issue by philfreo** [nervetattoo/jquery-autosave#26]
I use the `interval` trigger combined with the `modified` condition with this goal: "save anytime a form (textarea) is modified, but don't save more often than once per X seconds"

However this can lead to the final keystroke(s) never triggering a save, if it occurs after the last saving `interval` tick.

How do you suggest this be fixed?

/cc @thomasst

**Comment by thomasst** [comment]
You will need https://github.com/elasticsales/jquery-autosave/commit/34b3c74559002c61baa7ba3ad90db850b1b074ec and then call `next(false, false)`

**Comment by philfreo** [comment]
Oh, didn't realize this was already fixed. Can you submit a pull request?
