### ISSUE TITLE
send additional field including the changed one? 

### ISSUE THREAD

**Issue by anilex** [nervetattoo/jquery-autosave#27]
Hi, I am not sure I understand it from the readme. Could you give me a hint if it is possible to send the value of the changed field including another single form field "token"? And how to do it, if it possible. Thanks in advance!

**Comment by kflorence** [comment]
Yes, it's possible. You need to use the 'changed' scope and then add a custom scoping method of your own:

``` javascript
$("form").autosave({
    callbacks: {
        scope: [
            'changed',
            function(options, $inputs) {
                return $inputs.add('[name="token"]');
            }
        ]
    }
});
```

**Comment by anilex** [comment]
Great, it is working as expected. 
Sorry to bother you with another question.. I believe that it is possible to configure the callbacks settings to handle the changed field validation with some jquery validate plugin and to handle the returned server side field validation messages? I know how to use the validation plugin but I am wandering how to attach it to the autosave options. Thanks!

**Comment by kflorence** [comment]
I would implement validation inside of a [condition callback](https://github.com/nervetattoo/jquery-autosave#conditions), that way you can prevent save from being called if validation fails.
