### ISSUE TITLE
Collects data of all forms when apllied to multiple forms

### ISSUE THREAD

**Issue by NeoBelerophon** [nervetattoo/jquery-autosave#34]
Hi,

I have a grid with a form per row. And added autosave by 
$('#grid form').autosave .... 
when I set scope to all .. it collects all data of all forms. 
Is this a bug or do I have to apply autosave to each form on its own?

**Comment by kflorence** [comment]
Autosave will use all forms and inputs found for the given selector, if you want to limit the data collected to a single form, you can do so by providing a custom scope method, or by initializing autosave instances per form (depending on your use case).
