### ISSUE TITLE
Ajax error callback is not called.

### ISSUE THREAD

**Issue by rduplain** [nervetattoo/jquery-autosave#7]
I forked index.html from `examples/`.  When I bring the server down and trigger an autosave, the success callback is fired, not the error callback even though the ajax call is getting a refused connection.  (I'm on Ubuntu 11.10 with Google Chrome 15.0.874.106.)

Code is here:
https://github.com/rduplain/flask-jquery-autosave-example/blob/master/templates/index.html

Am I missing something, or is this a bug?

**Comment by kflorence** [comment]
The autosave AJAX call is just a wrapper for jQuery.ajax, so most likely this is the designed behavior. I have noticed certain circumstances in the past where jQuery.ajax wasn't firing the error handler when it should, but I can't remember the cases. In any case, it's not a bug in the autosave plugin, but thanks for reporting!
